name: vi
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - ipywidgets
  - pylint
  - rope
  - nodejs
  - nbdev
  - pytorch>=1.7.1
  - torchvision
  - fastai>=2.2.5
  - matplotlib
  - seaborn
  - spacy
  - cupy
  - wordcloud
  - python-Levenshtein
  - wandb
  - pip
  - pip:
    - imbalanced-learn
    - torchsummary
    - gensim
